services:
  - type: web
    name: pdpl-accident-prediction-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python -m app.ml.train
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
